---
- osx_say:
    msg: 'common role is started'
    voice: "{{ osx_voice }}"
  delegate_to: localhost
  when: ansible_os_family == 'Darwin'

- name: "Set USER_HOME env var facts"
  set_fact:
    USER_HOME: "{{ lookup('env','HOME') }}"
  tags:
    - always

- debug:
    msg:
      - 'Error in env; HOME env variable does not exist.  Please set!'
  when: not USER_HOME
  failed_when: not USER_HOME
  tags:
    - always
