---
- hosts: localhost
  become: False
  vars_files:
    - vars/global.yml
  roles:
    - common
  tasks:
    - osx_say:
        msg: 'hello world'
        voice: "{{ osx_voice }}"
      delegate_to: localhost
      when: ansible_os_family == 'Darwin'
